name: VR APK Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Unity Build (Android)
    runs-on: windows-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Frigjør diskplass (Windows)
        run: |
          # Sletter unødvendige verktøy for å få ca 5-10GB ekstra
          Remove-Item -Recurse -Force "C:\hostedtoolcache\windows\CodeQL" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force "C:\hostedtoolcache\windows\Ruby" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force "C:\hostedtoolcache\windows\Go" -ErrorAction SilentlyContinue
        shell: powershell

      - name: Cacher Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-Windows
          restore-keys: |
            Library-Android-

      - name: Fikser Unity License
        shell: powershell
        env:
          # Sender secrets.UNITY_LICENSE som en variabel i stedet for å injisere den i koden
          RAW_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          $dir = "C:\ProgramData\Unity\config"
          if (!(Test-Path $dir)) {
              New-Item -ItemType Directory -Force -Path $dir
          }
          
          # Henter innholdet fra miljøvariabelen og lagrer som fil
          $licenseContent = $env:RAW_LICENSE
          if ([string]::IsNullOrWhiteSpace($licenseContent)) { 
              throw "UNITY_LICENSE er tom! Sjekk GitHub Secrets." 
          }
          
          $licenseContent | Out-File -FilePath "$dir\ulf.xml" -Encoding ascii
          Write-Host "Lisensfil er skrevet til $dir\ulf.xml"

      - name: Bygger Unity Prosjekt
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          androidExportType: androidPackage
          buildname: VR_Simulator_Build

      - name: Lager Github Versjon
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: v0.1.${{ github.run_number }}
          name: Build v0.1.${{ github.run_number }}
          files: build/Android/VR_Simulator_Build.apk
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
